### PR TITLE
Improvements on the Alexa connector.

### PR DESCRIPTION
**Pull request by UpEsteban**
We have added to the posibility of sending several messages.
We have implemented the Hero Card Carousel parser to Directives List Template 1.
We have implemented the functionality that allows the Cards to return data through the Token field.
Improvement in the sending of messages (we pass all the simple messages to cards so that they are shown and we pass the simple cards to messages of voice to reproduce).

### CODE REVIEW

**Comment by garypretty** [comment]
Thanks for the PR! I will review over the next couple of days.

**Comment by garypretty** [comment]
Thanks again for the PR - there are some interesting changes / enhancements in here. We are currently in the process of considering how the Alexa and other custom adapters should be developed and what the roadmap looks like.  My plan right now is to leave this PR open until we get some of that planning underway and understand how we can fold it in. Thanks again!

**Comment by UpEsteban** [comment]
> 
> 
> Thanks again for the PR - there are some interesting changes / enhancements in here. We are currently in the process of considering how the Alexa and other custom adapters should be developed and what the roadmap looks like. My plan right now is to leave this PR open until we get some of that planning underway and understand how we can fold it in. Thanks again!

**Comment by UpEsteban** [comment]
Thank you very much, I will be waiting for the new improvements.

**Pull request closed without merging**
