### PR TITLE
Move Facebook, Slack, Twilio, Webex adapters

### PR DESCRIPTION
**Pull request by mrivera-ms**
This change adds the Bot Framework adapters currently in [Bot Framework SDK C#](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Adapters) and their unit tests.

In this change:

- Add Adapters source for Facebook, Slack, Twilio, Webex
- Add Unit tests
- Update README

### CODE REVIEW

**Comment by rvinothrajendran** [comment]
Hi @mrivera-ms 
Bot composer component namespace should be aligned with standard namespace like “Bot.Builder.Community.Components.” instead of Bot.Builder.Community.Adapters

**Comment by mrivera-ms** [comment]
> Hi @mrivera-ms Bot composer component namespace should be aligned with standard namespace like “Bot.Builder.Community.Components.Adapters” instead of Bot.Builder.Community.Adapters

Thanks for the comment @rvinothrajendran. However, these adapters are not related to Composer. Can you please clarify?

**Comment by rvinothrajendran** [comment]
> Components

Thank you. @mrivera-ms 
In this case, I think we have to remove the BotCompoent class files  (ex: FacebookAdapterBotComponent class)
In the future, enabling components for the composer we can create separate projects only for component files & Schemas

**Comment by garypretty** [comment]
> > Components
> 
> Thank you. @mrivera-ms In this case, I think we have to remove the BotCompoent class files (ex: FacebookAdapterBotComponent class) In the future, enabling components for the composer we can create separate projects only for component files & Schemas

I am going to accept this PR, given it is quite large and I want to get some others in behind it. We can retrospectively move the bot component class to another project if we want to.

**Pull request merged**
