### PR TITLE
Resolved #129

### LINKED ISSUE #129: Adapters.Alexa missing escape for ampersand in SSML response
Using an ampersand in a response results in the following (as I believe '&' isn't supported in SSML):

Invalid SSML Output Speech for requestId XXXXXXXX. Error: Fatal error occured when processing SSML content. This usually happens when the SSML is not well formed. Error: Unexpected character ' ' (code 32) (missing name?)\n at [row,col {unknown-source}]: [1,XX]

Replacing the '&' with 'and' fixes this, but it'd be nice to do this by default. As this is only for speech and not text (so '&' and 'and' are equivalent), it's probably best to build in a straight swap.

### PR DESCRIPTION
**Pull request by arafattehsin**
I have replaced the '&' with 'and' in the code for Alexa and Google Adapters. For your review, @garypretty

### CODE REVIEW

**Comment by iMicknl** [comment]
Could you escape all characters [not allowed by XML/SSML](https://stackoverflow.com/a/53020501/3554973).

**Comment by arafattehsin** [comment]
Thanks for the pointer Mich, closing this PR to be re-submitted again after escaping all the characters listed in the link.

**Comment by iMicknl** [comment]
@arafattehsin, have a look at the default functions for [escaping XML characters](https://docs.microsoft.com/en-us/dotnet/api/system.security.securityelement.escape). Maybe they can be useful. :-)

**Comment by arafattehsin** [comment]
Spot on! That's where I was looking at. Thanks again :)

**Pull request closed without merging**
