### PR TITLE
[TwitterAdapter] Add unit tests

### PR DESCRIPTION
**Pull request by santgr11**
### Description
This pull request adds Unit Test for the Twitter Adapter.

### Changes made
We added the project `Bot.Builder.Community.Adapters.Twitter.Tests` in the Tests folder.
We the following classes with unit tests, corresponding to classes from the Twitter Adapter.
- WebhookHostingServiceTests.cs
- WebhookMiddlewareTests.cs
- AuthHeaderBuilderTests.cs
- DirectMessageSenderTests.cs
- SubscriptionsManagerTests.cs
- WebhookInterceptorTests.cs
- WebhooksEnterpriseManagerTests.cs
- WebhooksPremiumManagerTests.cs
- ActivityExtensionsTests.cs
- TwitterAdapterTests.cs

These tests do not cover parts of the code using HttpClients, as we found we would require to edit the adapter so we can use a mocked client.

With these tests, we covered 30% of the TwitterAdapter project.
### Testing
image

### CODE REVIEW

**Comment by arafattehsin** [comment]
Thank you for your contribution @santgr11

**Comment by marcasmar94** [comment]
Quick question, Does this adapter support the below: 

- Getting the Postback payload from quick replies 
- Sending Media Attachments ( Pictures/Videos )
- Adding middlewares to it (Transcript, Auto save state etc.)

Thank you,

**Comment by garypretty** [comment]
@marcasmar94 I am unsure as per your preview features query.  This adapter is on my list to deep dive into over the next couple of weeks, so I will re-visit those features then. For middleware specifically, there is an open bug suggesting middleware is not supported at the moment, which I should be able to fix very easily.

**Comment by marcasmar94** [comment]
@garypretty  
Thank you Gary, I appreciate your help. 

I have once edited a previous version of the adapter and added support for Quick Replies Payload and Middlewares, But I had refactored it completely and followed how Alexa and Google adapters were made.
Since you guys made a lot of changes to adapters, I will wait your version and test that out.

As for Media attachments, I had a hard time for that and ended up ditching that feature **for now** (even though it is requested by one of our clients)

From what I remember, to be able to send an attachment on Twitter, we have to upload it there and send it by ID and not just send a URL attachment like other channels. Their documentation were a bit fuzzy and I did not find an library to handle that part directly.

Thank you again! I will test the new adapter as soon as its pushed.
Marc

**Pull request merged**
