### PR TITLE
Support EndOfConversation message from the bot when we can

### PR DESCRIPTION
**Pull request by NickEricson**
Support bot sending and EndOfConversation activity in the response to Alexa. This will be converted to the ShouldEndSession property.

When an EndOfConversation activity is seen end the session either via the directive or through the property.

### CODE REVIEW

**Comment by garypretty** [comment]
@NickEricson I want to check on something before we merge this - there is a open issue surrounding Teams not accepting the EndOfConversation and throwing an error and I believe the solution that has been put in place might be that that type of activity will now be prevented from hitting the channel.  We should check before adding this.

**Comment by NickEricson** [comment]
@garypretty I looked it up in the docs. They seem to differ a bit depending on where you look. From v3 docs:

https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-activities?view=azure-bot-service-3.0#endofconversation

`A bot receives an endOfConversation activity to indicate that the user has ended the conversation. A bot may send an endOfConversation activity to indicate to the user that the conversation is ending.`

and for v4
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-end-conversation?view=azure-bot-service-4.0

it seems some channels support it and some do not

`While the endOfConversation event is only sent by very few channels, the Cortana channel is the only one that accepts it. Other channels, including Direct Line, do not implement this functionality and instead drop or forward the activity on; each channel determines how to react to an endOfConversation activity.`

**Comment by garypretty** [comment]
@NickEricson I think we take this - I looked at the related PR and it doesn't look like it will cause us an issue.

**Comment by NickEricson** [comment]
Sounds good @garypretty , thanks for looking.

**Pull request merged**
