### PR TITLE
Extended Sentiment Analysis Middleware with on-device Sentiment Analyzer

### PR DESCRIPTION
**Pull request by arafattehsin**
Also, updated the relevant sample.

### CODE REVIEW

**Comment by garypretty** [comment]
@arafattehsin Could you resolve the conflicts please? Thanks.

**Comment by arafattehsin** [comment]
Oh sure! I will do this in a while.

**Comment by garypretty** [comment]
@arafattehsin  Thanks.No rush. I am travelling most of the next day so won't get back to this until tomorrow.

**Comment by arafattehsin** [comment]
@garypretty Sure, safe travels. I have resolved the conflicts.

**Comment by arafattehsin** [comment]
Hi @garypretty, can you please review and merge this!

**Pull request merged**
