### PR TITLE
add voiceprint support for Alexa

### PR DESCRIPTION
**Pull request by jamesemann**
#### Background

This PR adds a `person` field to the `AlexaSystem` class to support voiceprint on Alexa devices. (note that there is a subtle distinction between `user` (who registered the skill on the device) and `person` (the voiceprint, i.e. who interacted with the skill).

Referencing the Amazon docs:  https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html#system-object

```
{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "amzn1.echo-api.session.[unique-value-here]",
    "application": {
      "applicationId": "amzn1.ask.skill.[unique-value-here]"
    },
    "attributes": {
      "key": "string value"
    },
    "user": {
      "userId": "amzn1.ask.account.[unique-value-here]",
      "accessToken": "Atza|AAAAAAAA...",
      "permissions": {
        "consentToken": "ZZZZZZZ..."
      }
    }
  },
  "context": {
    "System": {
      "device": {
        "deviceId": "string",
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      },
      "application": {
        "applicationId": "amzn1.ask.skill.[unique-value-here]"
      },
      "user": {
        "userId": "amzn1.ask.account.[unique-value-here]",
        "accessToken": "Atza|AAAAAAAA...",
        "permissions": {
          "consentToken": "ZZZZZZZ..."
        }
      },
      "person": {
        "personId": "amzn1.ask.account.[unique-value-here]",
        "accessToken": "Atza|BBBBBBB..."
      },
      "apiEndpoint": "https://api.amazonalexa.com",
      "apiAccessToken": "AxThk..."
    },
    "AudioPlayer": {
      "playerActivity": "PLAYING",
      "token": "audioplayer-token",
      "offsetInMilliseconds": 0
    }
  },
  "request": {}
}
```

#### Testing this PR

Ping your Alexa endpoint through Alexa Developer Console and ensure that the ChannelData contains the data - e.g. by inspecting `turnContext.Activity.ChannelData.Context.System.Person`.

### CODE REVIEW

**Comment by garypretty** [comment]
@jamesemann Thanks for the PR - I have a feeling though that this may not be required with the version we have in preview now hanging off the Alexa.NET NuGet package, which should represent the person field. Can you try the version on the adopt-alexadotnet branch please?

**Comment by garypretty** [comment]
@jamesemann I might take this change anyway so that we can release an update to the current version with this in.  It would be great though if you could try implementing the preview version of the Adapter by grabbing the package from MyGet. You will need to update a few namespaces, but it should be relatively straightforward.

Details can be found here -> https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/feature/adopt-alexadotnet/libraries/Bot.Builder.Community.Adapters.Alexa/README.md

**Comment by jamesemann** [comment]
@garypretty will look at creating a preview version today - thank you!

Regarding Alexa.NET - `person` may also be missing from there - is this the library? - https://github.com/timheuer/alexa-skills-dotnet/blob/master/Alexa.NET/Request/Session.cs

**Comment by garypretty** [comment]
@jamesemann thanks. If it is missing from Alexa.NET then we can take a PR here and release an update from master, if you can also submit a PR to Alexa.NET to resolve the issue for the updated adapter with that dependency. Thanks.

Will be great to know how you get on with updating to the latest adapter too!

**Comment by jamesemann** [comment]
Verified this works in 4.6.6-rc0010. Thank you for your help!

For info to anyone looking to use Alexa voiceprint you need to go into your skill in Alexa Developer Console and enable the **Skills Personalization** permission.

image

**Pull request merged**
